# chuyển col link fb sang txt phù hợp với việc check

In [1]:
import pandas as pd

data = pd.read_csv('/home/tuong/Job/data /combined_dataset.csv')

data.head()

,Ngày tìm,Tên KH,SĐT,Nhà mạng,SĐT 2,Nhà mạng 2,Số lần tìm,Email,Emails,Giới tính,Ngày sinh,Location,Comment,Facebook
0,14-05-2026 16:42:17,Nhật Huy,896140216,MobiFone,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100068964922917
1,14-05-2026 16:42:00,Bùi Thanh Huỳnh,985203556,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,Hà Nội,NaN,https://fb.com/100004164218094
2,14-05-2026 16:41:54,Thanh Lâm,528802924,Vietnamobile,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/61578610755856
3,14-05-2026 16:41:14,Nhóc Lì,367721401,Viettel,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100093852491921
4,14-05-2026 16:38:29,Đầu Lông Cu,369512257,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,NaN,NaN,https://fb.com/100011627200357

In [2]:
#tách name và facebook link
df = data[['Tên KH', 'Facebook']]
df.head()

            Tên KH                        Facebook
0         Nhật Huy  https://fb.com/100068964922917
1  Bùi Thanh Huỳnh  https://fb.com/100004164218094
2        Thanh Lâm   https://fb.com/61578610755856
3          Nhóc Lì  https://fb.com/100093852491921
4      Đầu Lông Cu  https://fb.com/100011627200357

In [3]:
test_data = pd.read_csv("/home/tuong/Job/data /combined_dataset.csv")
test_data.head()

,Ngày tìm,Tên KH,SĐT,Nhà mạng,SĐT 2,Nhà mạng 2,Số lần tìm,Email,Emails,Giới tính,Ngày sinh,Location,Comment,Facebook
0,14-05-2026 16:42:17,Nhật Huy,896140216,MobiFone,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100068964922917
1,14-05-2026 16:42:00,Bùi Thanh Huỳnh,985203556,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,Hà Nội,NaN,https://fb.com/100004164218094
2,14-05-2026 16:41:54,Thanh Lâm,528802924,Vietnamobile,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/61578610755856
3,14-05-2026 16:41:14,Nhóc Lì,367721401,Viettel,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100093852491921
4,14-05-2026 16:38:29,Đầu Lông Cu,369512257,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,NaN,NaN,https://fb.com/100011627200357

In [4]:
data_checkVer1 = pd.read_csv("/home/tuong/Job/ket_qua.csv")
data_checkVer1.head()

,Tên KH,URL,Trạng thái,HTTP Code,Ghi chú,Thời gian (ms),Giờ check
0,Nhật Huy,https://fb.com/100068964922917,unknown,400,Bad Request,827,10:45:22
1,Bùi Thanh Huỳnh,https://fb.com/100004164218094,alive,200,Còn sống,825,10:45:22
2,Thanh Lâm,https://fb.com/61578610755856,alive,200,Còn sống,824,10:45:22
3,Nhóc Lì,https://fb.com/100093852491921,alive,200,Còn sống,824,10:45:22
4,Đầu Lông Cu,https://fb.com/100011627200357,unknown,400,Bad Request,826,10:45:22

In [11]:
#lọc ra những khách hàng có link còn sống và lưu vào data_alive
data_alive = data_checkVer1[data_checkVer1['Trạng thái'] == 'alive']
data_alive.head()

,Tên KH,URL,Trạng thái,HTTP Code,Ghi chú,Thời gian (ms),Giờ check
1,Bùi Thanh Huỳnh,https://fb.com/100004164218094,alive,200,Còn sống,825,10:45:22
2,Thanh Lâm,https://fb.com/61578610755856,alive,200,Còn sống,824,10:45:22
3,Nhóc Lì,https://fb.com/100093852491921,alive,200,Còn sống,824,10:45:22
7,Agustin Armando,https://fb.com/100004712827979,alive,200,Còn sống,886,10:45:23
8,Govind Badiyari Badiyari,https://fb.com/100005357824692,alive,200,Còn sống,555,10:45:23

In [ ]:
#lọc ra những khách hàng tên có cụm từ bđs và lưu vào data_bds
data_bds = data[data_alive['Tên KH'].str.contains('bđs', case=False, na=False)]
data_bds.head()

,Tên KH,URL,Trạng thái,HTTP Code,Ghi chú,Thời gian (ms),Giờ check
1342,Hoàng Phương Bđs,https://fb.com/100031679923175,alive,200,Còn sống,1590,10:48:58
1368,Thu Hiền Bđs,https://fb.com/100011556875868,alive,200,Còn sống,688,10:49:00
1465,Hoang Bđs,https://fb.com/61567589257374,alive,200,Còn sống,470,10:49:15
1637,Bđs Phú Yên New,https://fb.com/100090342471795,alive,200,Còn sống,461,10:49:43
1653,Bđs Quế Võ,https://fb.com/100010103712461,alive,200,Còn sống,461,10:49:46