# chuyển col link fb sang txt phù hợp với việc check

In [28]:
import pandas as pd

data = pd.read_csv('/home/tuong/Job/data /combined_dataset.csv')

data.head()

,Ngày tìm,Tên KH,SĐT,Nhà mạng,SĐT 2,Nhà mạng 2,Số lần tìm,Email,Emails,Giới tính,Ngày sinh,Location,Comment,Facebook
0,14-05-2026 16:42:17,Nhật Huy,896140216,MobiFone,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100068964922917
1,14-05-2026 16:42:00,Bùi Thanh Huỳnh,985203556,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,Hà Nội,NaN,https://fb.com/100004164218094
2,14-05-2026 16:41:54,Thanh Lâm,528802924,Vietnamobile,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/61578610755856
3,14-05-2026 16:41:14,Nhóc Lì,367721401,Viettel,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100093852491921
4,14-05-2026 16:38:29,Đầu Lông Cu,369512257,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,NaN,NaN,https://fb.com/100011627200357

In [29]:
#tách name và facebook link
df = data[['Tên KH', 'Facebook']]
df.head()

            Tên KH                        Facebook
0         Nhật Huy  https://fb.com/100068964922917
1  Bùi Thanh Huỳnh  https://fb.com/100004164218094
2        Thanh Lâm   https://fb.com/61578610755856
3          Nhóc Lì  https://fb.com/100093852491921
4      Đầu Lông Cu  https://fb.com/100011627200357

In [30]:
test_data = pd.read_csv("/home/tuong/Job/data /combined_dataset.csv")
test_data.head()

,Ngày tìm,Tên KH,SĐT,Nhà mạng,SĐT 2,Nhà mạng 2,Số lần tìm,Email,Emails,Giới tính,Ngày sinh,Location,Comment,Facebook
0,14-05-2026 16:42:17,Nhật Huy,896140216,MobiFone,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100068964922917
1,14-05-2026 16:42:00,Bùi Thanh Huỳnh,985203556,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,Hà Nội,NaN,https://fb.com/100004164218094
2,14-05-2026 16:41:54,Thanh Lâm,528802924,Vietnamobile,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/61578610755856
3,14-05-2026 16:41:14,Nhóc Lì,367721401,Viettel,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,https://fb.com/100093852491921
4,14-05-2026 16:38:29,Đầu Lông Cu,369512257,Viettel,NaN,NaN,1,NaN,NaN,Nam,NaN,NaN,NaN,https://fb.com/100011627200357

In [31]:
#tách Tên KH và Facebook và SĐT vào một dataframe mới
df = test_data[['Tên KH', 'Facebook', 'SĐT', 'SĐT 2']]
df.head()

            Tên KH                        Facebook        SĐT  SĐT 2
0         Nhật Huy  https://fb.com/100068964922917  896140216    NaN
1  Bùi Thanh Huỳnh  https://fb.com/100004164218094  985203556    NaN
2        Thanh Lâm   https://fb.com/61578610755856  528802924    NaN
3          Nhóc Lì  https://fb.com/100093852491921  367721401    NaN
4      Đầu Lông Cu  https://fb.com/100011627200357  369512257    NaN

In [33]:
#đổi kiểu dữ liệu của cột SĐT và SĐT 2 thành chuỗi và thêm 0 vào đầu số điện thoại nếu nó không có 0 ở đầu
df['SĐT'] = df['SĐT'].astype(str).str.replace(r'\D', '', regex=True)
df['SĐT'] = df['SĐT'].str.pad(width=10, side='left', fillchar='0')
df['SĐT 2'] = df['SĐT 2'].astype(str).str.replace(r'\D', '', regex=True)
df['SĐT 2'] = df['SĐT 2'].str.pad(width=10, side='left', fillchar='0')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5364 entries, 0 to 5363
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Tên KH    5364 non-null   str
 1   Facebook  5364 non-null   str
 2   SĐT       5364 non-null   str
 3   SĐT 2     2329 non-null   str
dtypes: str(4)
memory usage: 167.8 KB

In [ ]:
result_data_checkVer1 = pd.read_csv("/home/tuong/Job/ket_qua.csv")
result_data_checkVer1.info

<bound method DataFrame.info of                  Tên KH                             URL Trạng thái  HTTP Code  \
0              Nhật Huy  https://fb.com/100068964922917    unknown        400
1       Bùi Thanh Huỳnh  https://fb.com/100004164218094      alive        200
2             Thanh Lâm   https://fb.com/61578610755856      alive        200
3               Nhóc Lì  https://fb.com/100093852491921      alive        200
4           Đầu Lông Cu  https://fb.com/100011627200357    unknown        400
...                 ...                             ...        ...        ...
6034  Lê Thị Thanh Trúc  https://fb.com/100094685431409      alive        200
6035      Nguyễn Khương  https://fb.com/100049694807367    unknown        400
6036           Trọng Lê  https://fb.com/100016029695721    unknown        400
6037       Leon Trading   https://fb.com/61589399545227      alive        200
6038          Trân Trân   https://fb.com/61582797509861      alive        200

          Ghi chú  Thời gian (ms) Giờ check
0     Bad Request             827  10:45:22
1        Còn sống             825  10:45:22
2        Còn sống             824  10:45:22
3        Còn sống             824  10:45:22
4     Bad Request             826  10:45:22
...           ...             ...       ...
6034     Còn sống            6833  11:01:49
6035  Bad Request             476  11:01:43
6036  Bad Request             495  11:01:43
6037     Còn sống             727  11:01:43
6038     Còn sống             459  11:01:43

[6039 rows x 7 columns]>

In [36]:
# lưu dataframe mới vào một file csv
df.to_excel("/home/tuong/Job/data /cleaned_dataset.xlsx", index=False)